--from kettle 5 to 8
ALTER TABLE  R_STEP ADD COLUMN COPIES_STRING VARCHAR(255);
ALTER TABLE  R_DATABASE ADD COLUMN INSTANCE_NAME VARCHAR(255);

--add interface restriction 20191104
ALTER TABLE `T_SERVICE_AUTH` ADD COLUMN `LINES_LIMIT` bigint(20) NULL COMMENT '限制条数';
ALTER TABLE `T_SERVICE_AUTH` ADD COLUMN `CYCLE_LIMIT` int(11) NULL COMMENT '限制周期 1:分钟 2:小时 3:天';
ALTER TABLE `T_SERVICE_AUTH` ADD COLUMN `CYCLE_LIMIT` int(11) NULL COMMENT '限制时间';
ALTER TABLE `T_SERVICE_MONITOR` ADD COLUMN `PARAMS` varchar(255) NULL COMMENT '请求参数';
ALTER TABLE `T_SERVICE_MONITOR` ADD COLUMN `LINES_OUTPUT` bigint(20) NULL COMMENT '输出记录数';

--add mdm attribute desc 20191104
ALTER TABLE `MDM_MODEL_ATTRIBUTE` ADD COLUMN `ATTRIBUTE_DESC` varchar(1000) NULL COMMENT '属性描述注释';
ALTER TABLE `MDM_MODEL_ATTRIBUTE` ADD COLUMN `FIELD_DEFULT` int(11) NULL COMMENT '字段缺省值';
ALTER TABLE `MDM_MODEL_ATTRIBUTE` ADD COLUMN `FIELD_IS_NULL` int(11) NULL COMMENT '字段是否可以为空';
